export const ActionTypes = {
    USER_SIGNUP: "USER_SIGNUP",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    ADDTODO_ERROR: "ADDTODO_ERROR",
    ADD_TODO: "ADD_TODO",
    TODO_DATA: "TODO_DATA",
    DELETE_TODO: "DELETE_TODO",
    EDIT_TODO: "EDIT_TODO"
}